[theme]
base = "light"
primaryColor = "#2E86AB"          # Professional blue (education-friendly)
backgroundColor = "#FFFFFF"        # Pure white
secondaryBackgroundColor = "#F8F9FA"  # Light gray for cards
textColor = "#2C3E50"             # Dark blue-gray (readable)
font = "sans serif"
