[theme]
base = "light"
primaryColor = "#1565C0"          # Material Design blue
backgroundColor = "#FAFAFA"        # Soft off-white
secondaryBackgroundColor = "#F5F5F5"  # Light gray
textColor = "#37474F"             # Blue-gray text
font = "sans serif"
