[theme]
base = "dark"
primaryColor = "#3498db"          # Your custom blue
backgroundColor = "#0e1117"       # Dark background
secondaryBackgroundColor = "#262730"  # Slightly lighter for cards
textColor = "#fafafa"            # Light text
font = "sans serif"              # Clean, professional font
